### PR TITLE
configure cpu numbers

### PR DESCRIPTION
**Pull request by longshuicy**
Conclusion, 14 CPUs is the fastest.
~~WIP playing with different cpu numbers and calculate time.~~

### CODE REVIEW

**Review by robkooper — APPROVED** [review]
nice work of bumping changelog and chart values

**Review by ywkim312 — COMMENTED** [review]
Please update line 50 of Chart.yaml

**Review by ywkim312 — CHANGES_REQUESTED** [review]
Please update line 50 of Chart.yaml

**Comment by longshuicy** [comment]
> Please update line 50 of Chart.yaml

Im not releasing incore for this PR so it might stay at 5.2.0?

**Comment by robkooper** [comment]
no it should show what has changed in the helm chart. see https://artifacthub.io/packages/helm/ncsa/incore?modal=changelog

**Review by ywkim312 — APPROVED** [review]

**Pull request merged**
