### PR TITLE
122 shorten the slc retrofit key

### PR DESCRIPTION
**Pull request by longshuicy**

### CODE REVIEW

**Comment by Rashmil-1999** [comment]
So, with this, did we need to change anything in terms of code?

**Comment by Rashmil-1999** [comment]
and did we map these values in the maestro/datawolf then?

**Comment by longshuicy** [comment]
> So, with this, did we need to change anything in terms of code?

I dont think so. The RS builder is writing whatever key the frontend (this config) sent. The only place I need to change is the fragility mapping 6309005ad76c6d0e1f6be081

**Comment by longshuicy** [comment]
> and did we map these values in the maestro/datawolf then?

Explanation see above :-)

**Review by Rashmil-1999 — APPROVED** [review]
Perfect, sounds good then! :)

**Review by Vismayak — APPROVED** [review]

**Pull request merged**
